parameters:
#    vintage_west_front.example.class: VintageWest\FrontBundle\Example

services:
#    vintage_west_front.example:
#        class: %vintage_west_front.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
