<?php

namespace VintageWest\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockRepository extends EntityRepository
{
    public function findAllCounted()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT COUNT(a) FROM VintageWestAdminBundle:Block a')
            ->getSingleScalarResult();
    }

    public function findAllByPageAndLanguage($page,$language){

        return $this->getEntityManager()
            ->createQuery('SELECT a FROM VintageWestAdminBundle:Block a LEFT JOIN a.type t WHERE a.page = :page AND a.lang = :language')
            ->setParameters(array('page'=>$page,'language'=>$language))
            ->getResult();

    }
}
