<?php

namespace VintageWest\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function findAllCounted()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT COUNT(a) FROM VintageWestAdminBundle:News a')
            ->getSingleScalarResult();
    }
}
