car:
    pattern:  /admin/car
    defaults: { _controller: VintageWestAdminBundle:Car:index }
car_create:
    pattern:  /admin/car/create
    defaults: { _controller: VintageWestAdminBundle:Car:create }
car_show:
    pattern:  /admin/car/{id}
    defaults: { _controller: VintageWestAdminBundle:Car:show }
car_delete:
    pattern:  /admin/car/delete/{id}
    defaults: { _controller: VintageWestAdminBundle:Car:delete }
car_edit:
    pattern:  /admin/car/edit/{id}
    defaults: { _controller: VintageWestAdminBundle:Car:edit }
car_update:
    pattern:  /admin/car/update/{id}
    defaults: { _controller: VintageWestAdminBundle:Car:update }
equipement:
    pattern:  /admin/equipement
    defaults: { _controller: VintageWestAdminBundle:Equipement:index }
equipement_create:
    pattern:  /admin/equipement/create
    defaults: { _controller: VintageWestAdminBundle:Equipement:create }
equipement_show:
    pattern:  /admin/equipement/{id}
    defaults: { _controller: VintageWestAdminBundle:Equipement:show }
equipement_delete:
    pattern:  /admin/equipement/delete/{id}
    defaults: { _controller: VintageWestAdminBundle:Equipement:delete }
equipement_edit:
    pattern:  /admin/equipement/edit/{id}
    defaults: { _controller: VintageWestAdminBundle:Equipement:edit }
equipement_update:
    pattern:  /admin/equipement/update/{id}
    defaults: { _controller: VintageWestAdminBundle:Equipement:update }
imageillustration:
    pattern:  /admin/illustration
    defaults: { _controller: VintageWestAdminBundle:ImageIllustration:index }
imageillustration_create:
    pattern:  /admin/illustration/create
    defaults: { _controller: VintageWestAdminBundle:ImageIllustration:create }
imageillustration_show:
    pattern:  /admin/illustration/{id}
    defaults: { _controller: VintageWestAdminBundle:ImageIllustration:show }
imageillustration_delete:
    pattern:  /admin/illustration/delete/{id}
    defaults: { _controller: VintageWestAdminBundle:ImageIllustration:delete }
imageillustration_edit:
    pattern:  /admin/illustration/edit/{id}
    defaults: { _controller: VintageWestAdminBundle:ImageIllustration:edit }
imageillustration_update:
    pattern:  /admin/illustration/update/{id}
    defaults: { _controller: VintageWestAdminBundle:ImageIllustration:update }
language:
    pattern:  /admin/language
    defaults: { _controller: VintageWestAdminBundle:Language:index }
language_create:
    pattern:  /admin/language/create
    defaults: { _controller: VintageWestAdminBundle:Language:create }
language_show:
    pattern:  /admin/language/{id}
    defaults: { _controller: VintageWestAdminBundle:Language:show }
language_delete:
    pattern:  /admin/language/delete/{id}
    defaults: { _controller: VintageWestAdminBundle:Language:delete }
language_edit:
    pattern:  /admin/language/edit/{id}
    defaults: { _controller: VintageWestAdminBundle:Language:edit }
language_update:
    pattern:  /admin/language/update/{id}
    defaults: { _controller: VintageWestAdminBundle:Language:update }
news:
    pattern:  /admin/news
    defaults: { _controller: VintageWestAdminBundle:News:index }
news_create:
    pattern:  /admin/news/create
    defaults: { _controller: VintageWestAdminBundle:News:create }
news_show:
    pattern:  /admin/news/{id}
    defaults: { _controller: VintageWestAdminBundle:News:show }
news_delete:
    pattern:  /admin/news/delete/{id}
    defaults: { _controller: VintageWestAdminBundle:News:delete }
news_edit:
    pattern:  /admin/news/edit/{id}
    defaults: { _controller: VintageWestAdminBundle:News:edit }
news_update:
    pattern:  /admin/news/update/{id}
    defaults: { _controller: VintageWestAdminBundle:News:update }
prestations:
    pattern:  /admin/prestations
    defaults: { _controller: VintageWestAdminBundle:Prestation:index }
prestations_create:
    pattern:  /admin/prestations/create
    defaults: { _controller: VintageWestAdminBundle:Prestation:create }
prestations_show:
    pattern:  /admin/prestations/{id}
    defaults: { _controller: VintageWestAdminBundle:Prestation:show }
prestations_delete:
    pattern:  /admin/prestations/delete/{id}
    defaults: { _controller: VintageWestAdminBundle:Prestation:delete }
prestations_edit:
    pattern:  /admin/prestations/edit/{id}
    defaults: { _controller: VintageWestAdminBundle:Prestation:edit }
prestations_update:
    pattern:  /admin/prestations/update/{id}
    defaults: { _controller: VintageWestAdminBundle:Prestation:update }