parameters:
#    vintage_west_admin.example.class: VintageWest\AdminBundle\Example

services:
#    vintage_west_admin.example:
#        class: %vintage_west_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
